### ISSUE TITLE
Python error shown on the console

### ISSUE THREAD

**Issue by RalfJung** [kalkin/gajim-omemo#26]
The following error is shown when I start Gajim with "./launch.sh", with the git master version of OMEMO:

```
10.01.2016 15:57:57 (W) gajim.plugin_system.omemo [JABBER-SERVER] → Device list needs updating
10.01.2016 15:58:05 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7f763f64ff50>>
Traceback (most recent call last):
  File "/home/r/src/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/r/src/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/r/.local/share/gajim/plugins/omemo/__init__.py", line 139, in message_received
    gui = self.ui_list[account].get(jid, None)
KeyError: u'[JABBER-SERVER]'
10.01.2016 15:58:05 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7f763f64ff50>>
Traceback (most recent call last):
  File "/home/r/src/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/r/src/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/r/.local/share/gajim/plugins/omemo/__init__.py", line 139, in message_received
    gui = self.ui_list[account].get(jid, None)
KeyError: u'[JABBER-SERVER]'
```

I never even tried using OMEMO encryption with that server (it's a fairly minor account), so it may well be that the server doesn't support PEP properly. I don't really care ;-) but these python exceptions looked fishy.

**Comment by kalkin** [comment]
@RalfJung If you like you can create me a test account on your server and E-Mail it to me. (My E-Mail is in the profile)

**Comment by RalfJung** [comment]
Sorry, that server is not mine but run by my institute. Only institute members get accounts. I'm happy to run debug code for you, though - just point me to a git branch of the OMEMO plugin I should run.

**Comment by t2d** [comment]
I get the same error on restart. Maybe it is a problem with messages from old sessions, which are replayed?

```
11.01.2016 12:53:48 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7efc8139ac50>>
Traceback (most recent call last):
  File "/usr/share/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/usr/share/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/t/.local/share/gajim/plugins/omemo/__init__.py", line 150, in message_received
    gui = self.ui_list[account].get(jid, None)
KeyError: u'account1@jabber.systemli.org'
```

**Comment by kalkin** [comment]
@t2d @RalfJung Please check if the error still exists in the current HEAD. 

Thanks in advance
kalkin-

**Comment by RalfJung** [comment]
I don't see the error any more. There's a different error though, which may mask this one:

```
14.01.2016 16:59:54 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.handle_iq_received of <omemo.OmemoPlugin object at 0x7f2b037b2f50>>
Traceback (most recent call last):
  File "/home/r/src/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/r/src/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/r/.local/share/gajim/plugins/omemo/__init__.py", line 266, in handle_iq_received
    iq_ids_to_callbacks[id_](event.stanza)
  File "/home/r/.local/share/gajim/plugins/omemo/__init__.py", line 397, in <lambda>
    self.handle_announcement_result(account, stanza, state)
  File "/home/r/src/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/r/.local/share/gajim/plugins/omemo/__init__.py", line 421, in handle_announcement_result
    self.publish_own_devices_list(state)
  File "/home/r/src/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
TypeError: publish_own_devices_list() takes exactly 3 arguments (2 given)
```

**Comment by RalfJung** [comment]
And now I do see the original error again, below the above cited new stacktrace.

**Comment by kalkin** [comment]
@RalfJung The new error should be fixed now in HEAD. Could you run try the current head and document the new error line numbers here for further bug searching?

**Comment by RalfJung** [comment]
The new error is fixed. The original one remains.

Here you go:

```
15.01.2016 17:31:33 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7f5fcaee9f50>>
Traceback (most recent call last):
  File "/home/r/src/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/r/src/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/r/.local/share/gajim/plugins/omemo/__init__.py", line 155, in message_received
    gui = self.ui_list[account].get(jid, None)
KeyError: u'<JABBER-SERVER>'
15.01.2016 17:31:33 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7f5fcaee9f50>>
Traceback (most recent call last):
  File "/home/r/src/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/r/src/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/r/.local/share/gajim/plugins/omemo/__init__.py", line 155, in message_received
    gui = self.ui_list[account].get(jid, None)
KeyError: u'<JABBER-SERVER>'
```

**Comment by t2d** [comment]
This error seems to be gone in 0.4

**Comment by kalkin** [comment]
@t2d Thank you for your feedback. @RalfJung I'm closing this now, because I assume it's fixed. If you still have issues, just comment here.

**Comment by RalfJung** [comment]
Nope, sorry, not fixed:

```
29.01.2016 11:16:01 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7f4282512f50>>
Traceback (most recent call last):
  File "/home/r/src/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/r/src/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/r/.local/share/gajim/plugins/omemo/__init__.py", line 155, in message_received
    gui = self.ui_list[account].get(jid, None)
KeyError: u'jabber.XXX'
29.01.2016 11:16:01 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7f4282512f50>>
Traceback (most recent call last):
  File "/home/r/src/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/r/src/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/r/.local/share/gajim/plugins/omemo/__init__.py", line 155, in message_received
    gui = self.ui_list[account].get(jid, None)
KeyError: u'jabber.XXX'
```

This is with d970936.

I can't re-open this issue. Should I open a new one?

**Comment by kalkin** [comment]
@t2d Are you sure it's fixed for you? Did you change something in your infrastructure, like ejabberd update?

@RalfJung I think only the maintainer is allowed to reopen issues?

**Comment by RalfJung** [comment]
In some bugtrackers, the original reported can reopen issues. Maybe not on github. _shrug_

Thanks for reopening :)

**Comment by kalkin** [comment]
Can you please try the current HEAD? I think @iNPUTmice fixed this

**Comment by RalfJung** [comment]
Nope, getting this error with current master:

```
$ ~/src/gajim/launch.sh 
abort: no repository found in '/home/r/src/gajim/src' (.hg not found)!
/home/r/.local/share/gajim/plugins/gotr/ui.py:40: GtkWarning: Unknown property: GtkMenu.ubuntu-local
  self.B.add_from_file(self.GTK_BUILDER_FILE_PATH)
/home/r/.local/lib/python2.7/site-packages/nbxmpp/tls_nb.py:436: DeprecationWarning: unicode for cipher_list is no longer accepted, use bytes
  tcpsock._sslContext.set_cipher_list(self.cipher_list)
04.05.2016 09:58:12 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7f2bfccca9d0>>
Traceback (most recent call last):
  File "/home/r/src/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/r/src/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/r/.local/share/gajim/plugins/omemo/__init__.py", line 160, in message_received
    gui = self.ui_list[account].get(jid, None)
KeyError: u'jabber.YYY'
04.05.2016 09:58:12 (W) gajim.plugin_system.omemo jabber.XXX → Device list needs updating
04.05.2016 09:58:20 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7f2bfccca9d0>>
Traceback (most recent call last):
  File "/home/r/src/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/r/src/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/r/.local/share/gajim/plugins/omemo/__init__.py", line 160, in message_received
    gui = self.ui_list[account].get(jid, None)
KeyError: u'jabber.XXX'
04.05.2016 09:58:20 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7f2bfccca9d0>>
Traceback (most recent call last):
  File "/home/r/src/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/r/src/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/r/.local/share/gajim/plugins/omemo/__init__.py", line 160, in message_received
    gui = self.ui_list[account].get(jid, None)
KeyError: u'jabber.XXX'
```

**Comment by kalkin** [comment]
@RalfJung can you please delete your omemo sql databases and strart from scratch?

**Comment by RalfJung** [comment]
Which file would that be? Which data would I lose?

**Comment by kalkin** [comment]
`rm -i ~/.local/share/gajim/omemo_*.db`

**Comment by RalfJung** [comment]
That doesn't answer the second part of my question: Which data would I lose? Is this just some temporary caches, or do I lose actual user data like the keys I accepted for peers?

**Comment by RalfJung** [comment]
Nope, it did not help. On first start after deleting the DB, I get

```
05.05.2016 11:56:48 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7fd164cd1d50>>
Traceback (most recent call last):
  File "/home/r/src/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/r/src/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/r/.local/share/gajim/plugins/omemo/__init__.py", line 160, in message_received
    gui = self.ui_list[account].get(jid, None)
KeyError: u'jabber.XXX'
05.05.2016 11:56:48 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7fd164cd1d50>>
Traceback (most recent call last):
  File "/home/r/src/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/r/src/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/r/.local/share/gajim/plugins/omemo/__init__.py", line 160, in message_received
    gui = self.ui_list[account].get(jid, None)
KeyError: u'jabber.XXX'
```

It is well possible that this Jabber server does not support some of the necessary XEPs. However, that should just lead to Omemo not working, it shouldn't result in uncaught exceptions.

**Comment by kalkin** [comment]
@RalfJung can you provide my an account on this jabber server for testing? You can send it me via mail. [GPG Key and Mail](http://bahtiar.gadimov.de/)

**Comment by RalfJung** [comment]
Unfortunately not -- this server is provided by my institute, and only institute members get an account. Sorry.

**Comment by kalkin** [comment]
Will add some debug code which will try to find out what is missing.

**Comment by alexacra** [comment]
`Gajim 0.16.5, conversations.im, omemo plugin 0.5.1, Ubuntu 16.04`

I see the same error about 25x times on the console after startup, the most appear at the same time:

```
10.06.2016 11:10:02 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7f058e4d53d0>>
Traceback (most recent call last):
  File "/usr/share/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/usr/share/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/mh/.local/share/gajim/plugins/omemo/__init__.py", line 160, in message_received
    gui = self.ui_list[account].get(jid, None)
KeyError: u'conversations.im'
```

**Comment by lovetox** [comment]
@alexara @RalfJung this error is already fixed, try my repo https://github.com/lovetox/gajim-omemo

it will get merged soon.

it only means, that it couldnt show a warning message, cause the chat window is not open

**Comment by kalkin** [comment]
Just as a warning: Using lovetox branch is **unsupported** and should only done by people who know what they are doing. I expect to merge the final version of lovetox changes in a few days.

**Comment by lovetox** [comment]
should be fixed in current HEAD
